# Generated by Django 3.1.2 on 2020-10-26 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_auto_20201026_1453'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_number', models.CharField(blank=True, max_length=12, verbose_name='Aadhar Number')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.address', verbose_name='Address')),
                ('service_areas', models.ManyToManyField(blank=True, to='service.DeliveryLocation')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Delivery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
