# Generated by Django 3.1.2 on 2020-10-26 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(default='mumbai', max_length=30, verbose_name='Landmark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='acno',
            field=models.CharField(default='1234', max_length=14, verbose_name='Account Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='axis', max_length=40, verbose_name='Bank Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bname',
            field=models.CharField(default='axos', max_length=50, verbose_name='Beneficiary Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.CharField(default='mumbai', max_length=40, verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ifsc',
            field=models.CharField(default='1234', max_length=15, verbose_name='IFSC Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='sub',
            field=models.BooleanField(default=False, verbose_name='Updates'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='tnc',
            field=models.BooleanField(default=True, verbose_name='Terms of Use'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.CharField(default='akash@test.com', max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Phone Number Must be entered in Valid Format', regex='\\w[\\w\\.-]*@\\w[\\w\\.-]+\\.\\w+')], verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailotp',
            name='forgot',
            field=models.BooleanField(default=False, help_text='Only True if Forgot Password'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='forgot_logged',
            field=models.BooleanField(default=False, help_text='Master Reset Logged?'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='logged',
            field=models.BooleanField(default=False, help_text='Was Verification Successful?'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(default='1234', max_length=9, verbose_name='OTP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='count',
            field=models.IntegerField(default=0, help_text='Number of OTP Sent', verbose_name='Number of OTP Sent'),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='forgot',
            field=models.BooleanField(default=False, help_text='Only True if Forgot Password'),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='forgot_logged',
            field=models.BooleanField(default=False, help_text='Master Reset Logged?'),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='logged',
            field=models.BooleanField(default=False, help_text='Was Verification Successful?'),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='otp',
            field=models.CharField(default='1234', max_length=9, verbose_name='OTP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(default='123', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone Number Must be entered in Valid Format', regex='^\\+?1?\\d{9,14}$')], verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
