# Generated by Django 3.1.2 on 2020-10-27 07:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20201027_1258'),
        ('service', '0002_auto_20201026_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Email Must be entered in Valid Format', regex='\\w[\\w\\.-]*@\\w[\\w\\.-]+\\.\\w+')], verbose_name='E-mail'),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.vendor')),
            ],
        ),
    ]
