# Generated by Django 3.1.2 on 2020-10-29 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_salereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
