# Generated by Django 3.1.2 on 2020-10-29 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
