# Generated by Django 3.1.2 on 2020-10-29 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
