# Generated by Django 3.1.2 on 2020-10-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201026_1453'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.bankaccount'),
        ),
    ]
