# Generated by Django 3.1.2 on 2020-10-29 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20201027_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
